/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressHandle: typeof import('./pages/goods/components/AddressHandle.vue')['default']
    CategoryPanel: typeof import('./pages/index/components/CategoryPanel.vue')['default']
    CateSkeleton: typeof import('./pages/category/components/CateSkeleton.vue')['default']
    CustomNavbar: typeof import('./pages/index/components/CustomNavbar.vue')['default']
    HotPanel: typeof import('./pages/index/components/HotPanel.vue')['default']
    PageSkeleton: typeof import('./pages/index/components/pageSkeleton.vue')['default']
    ServerPanel: typeof import('./pages/goods/components/ServerPanel.vue')['default']
    XtxGuess: typeof import('./components/XtxGuess.vue')['default']
    XtxSwiper: typeof import('./components/XtxSwiper.vue')['default']
  }
}
